<a href="https://colab.research.google.com/github/kaonashithank1022/data-analysis-basic-kadai/blob/main/text/2%E7%AB%A0_NumPy%E3%81%AE%E6%A6%82%E8%A6%81%E3%82%92%E7%90%86%E8%A7%A3%E3%81%97%E3%82%88%E3%81%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Step1.NumPyをインポートするコードを記述する
import numpy as np


np.random.rand()

0.9985402054944355

In [ ]:
import numpy as np

random_multi_array = np.random.randint(1, 10, (5,5))
random_multi_array


array([[7, 4, 3, 4, 2],
       [5, 5, 6, 9, 1],
       [2, 1, 7, 8, 7],
       [9, 5, 3, 2, 7],
       [6, 7, 1, 7, 3]])

In [ ]:
random_multi_array.max()

np.int64(9)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
six_reshape = np.arange(6).reshape(2, 3)
six_reshape

six_reshape + 1

six_reshape + np.array([[1, 0 ,2], [1, 0, 2]])

array([[1, 1, 4],
       [4, 4, 7]])

In [ ]:
# Step1.NumPyをインポートするコードを記述する
import numpy as np

# Step2.AとBの行列を格納する多次元配列のコードを記述する
A = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])

B = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

# Step3.行列の積の計算をするコードを記述する
C = np.dot(A, B)


# Step4.Step3.の計算結果を表示するコードを記述する
print("行列の積", C)


# Step5.行列の要素の最大値を求めるコードを記述する
max_value = C.max()  # np.max(C) でも可
print("最大値", max_value)

行列の積 [[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値 47


In [ ]:
# 【修正例】変数 C の種類（型）を調べたい場合
type()

TypeError: type() takes 1 or 3 arguments