<a href="https://colab.research.google.com/github/kaonashithank1022/data-analysis-basic-kadai/blob/main/text/kadai_003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPyで配列の操作や演算をしよう
3章までに学んだ知識を活かして、NumPyの配列操作をします。


**本課題の目標**


全般的に、1〜3章の内容を理解すること

NumPyをインポートできること

「多次元配列」を書けること

配列の操作ができること

行列演算ができること


**課題の内容**

NumPyを利用して、次の２つの行列の積を計算して結果を表示し、計算された行列の要素の最大値を求めて表示するコードを記述しましょう



**課題の参考**


1章 データ分析の概要を理解しよう
2章 NumPyでできること
3章 NumPyを使ってみよう
作業上の注意事項
行列を、多次元配列の記法で書く際に、行と列を入れ違えない様にしましょう


**課題の作業手順**

Step1.
NumPyをインポートするコードを記述する

Step2.
AとBの行列を格納する多次元配列のコードを記述する

Step3.
行列の積の計算をするコードを記述する

Step4.
Step3.の計算結果を表示するコードを記述する

Step5.
行列の要素の最大値を求めるコードを記述する



In [11]:
#Step1. NumPyをインポートするコードを記述する
import numpy as np

#Step2. AとBの行列を格納する多次元配列のコードを記述する
A = np.array([[0, 1], [2, 3],[4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

#Step3. 行列の積の計算をするコードを記述する
Product = np.dot(A, B)

#Step4. Step3.の計算結果を表示するコードを記述する
print(Product)

#Step5. 行列の要素の最大値を求めるコードを記述する
print(Product.max())

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
